# Generated by Django 3.0.3 on 2020-06-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('cno', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('qul', models.CharField(max_length=10)),
                ('select', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
            ],
        ),
    ]
