# Generated by Django 3.0.3 on 2020-06-04 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='college',
            name='doj',
        ),
        migrations.AddField(
            model_name='college',
            name='djj',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='dooo',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 4, 13, 10, 39, 766233, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
