# Generated by Django 3.0.3 on 2020-06-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20200604_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='dooo',
            new_name='doo',
        ),
    ]
