# Generated by Django 3.0.3 on 2020-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20200604_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='idno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
