# Generated by Django 3.0.3 on 2020-06-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=20)),
                ('cno', models.IntegerField()),
                ('bbb', models.DateField(blank=True)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('add', models.CharField(max_length=40)),
                ('balck', models.CharField(max_length=5)),
                ('course', models.CharField(max_length=5)),
                ('icetpie', models.ImageField(upload_to='acc_images/')),
                ('image', models.ImageField(upload_to='aurora/')),
                ('dname', models.CharField(max_length=30)),
                ('du', models.CharField(max_length=10)),
                ('dyop', models.IntegerField()),
                ('dtm', models.IntegerField()),
                ('iname', models.CharField(max_length=30)),
                ('iu', models.CharField(max_length=10)),
                ('iyop', models.IntegerField()),
                ('itm', models.IntegerField()),
                ('ssname', models.CharField(max_length=30)),
                ('su', models.CharField(max_length=10)),
                ('syop', models.IntegerField()),
                ('stm', models.IntegerField()),
            ],
        ),
    ]
