# Generated by Django 3.0.3 on 2020-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200607_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='icetpie',
            field=models.ImageField(upload_to='icet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
