# Generated by Django 3.0.3 on 2020-06-07 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200607_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='icetalloment',
            field=models.IntegerField(default=datetime.datetime(2020, 6, 7, 9, 2, 55, 470769, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
