# Generated by Django 3.0.3 on 2020-06-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_icetalloment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='icetalloment',
        ),
    ]
